// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tici/indexer.proto

/*
Package tipb is a generated protocol buffer package.

It is generated from these files:

	tici/indexer.proto

It has these top-level messages:

	CreateIndexRequest
	CreateIndexResponse
	DropIndexRequest
	DropIndexResponse
	TiCITableInfo
	TiCIColumnInfo
	TiCIIndexInfo
	ParserInfo
	GetIndexProgressRequest
	GetIndexProgressResponse
*/
package tipb

import (
	"fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	context "golang.org/x/net/context"

	grpc "google.golang.org/grpc"

	io "io"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// IndexType represents the type of index
type IndexType int32

const (
	// Default value must be 0 in proto3
	IndexType_UNKNOWN IndexType = 0
	// Full-text index type
	IndexType_FULL_TEXT IndexType = 1
	// Custom index type
	IndexType_CUSTOM IndexType = 2
)

var IndexType_name = map[int32]string{
	0: "UNKNOWN",
	1: "FULL_TEXT",
	2: "CUSTOM",
}
var IndexType_value = map[string]int32{
	"UNKNOWN":   0,
	"FULL_TEXT": 1,
	"CUSTOM":    2,
}

func (x IndexType) String() string {
	return proto.EnumName(IndexType_name, int32(x))
}
func (IndexType) EnumDescriptor() ([]byte, []int) { return fileDescriptorIndexer, []int{0} }

// ParserType represents the type of parser
type ParserType int32

const (
	// Default value must be 0 in proto3
	ParserType_UNKNOWN_PARSER ParserType = 0
	// Default parser
	ParserType_DEFAULT_PARSER ParserType = 1
	// Other parser types
	ParserType_OTHER_PARSER ParserType = 2
)

var ParserType_name = map[int32]string{
	0: "UNKNOWN_PARSER",
	1: "DEFAULT_PARSER",
	2: "OTHER_PARSER",
}
var ParserType_value = map[string]int32{
	"UNKNOWN_PARSER": 0,
	"DEFAULT_PARSER": 1,
	"OTHER_PARSER":   2,
}

func (x ParserType) String() string {
	return proto.EnumName(ParserType_name, int32(x))
}
func (ParserType) EnumDescriptor() ([]byte, []int) { return fileDescriptorIndexer, []int{1} }

// CreateIndexRequest is a request to create an index
type CreateIndexRequest struct {
	// Index information
	IndexInfo *TiCIIndexInfo `protobuf:"bytes,1,opt,name=index_info,json=indexInfo" json:"index_info,omitempty"`
	// Table information
	TableInfo *TiCITableInfo `protobuf:"bytes,2,opt,name=table_info,json=tableInfo" json:"table_info,omitempty"`
}

func (m *CreateIndexRequest) Reset()                    { *m = CreateIndexRequest{} }
func (m *CreateIndexRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateIndexRequest) ProtoMessage()               {}
func (*CreateIndexRequest) Descriptor() ([]byte, []int) { return fileDescriptorIndexer, []int{0} }

func (m *CreateIndexRequest) GetIndexInfo() *TiCIIndexInfo {
	if m != nil {
		return m.IndexInfo
	}
	return nil
}

func (m *CreateIndexRequest) GetTableInfo() *TiCITableInfo {
	if m != nil {
		return m.TableInfo
	}
	return nil
}

// CreateIndexResponse is a response to the index creation request
type CreateIndexResponse struct {
	// Operation result status code, 0 means success
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// Error message, only valid when status is non-zero
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Created index ID
	IndexId string `protobuf:"bytes,3,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
}

func (m *CreateIndexResponse) Reset()                    { *m = CreateIndexResponse{} }
func (m *CreateIndexResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateIndexResponse) ProtoMessage()               {}
func (*CreateIndexResponse) Descriptor() ([]byte, []int) { return fileDescriptorIndexer, []int{1} }

func (m *CreateIndexResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateIndexResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *CreateIndexResponse) GetIndexId() string {
	if m != nil {
		return m.IndexId
	}
	return ""
}

// DropIndexRequest is a request to drop an index
type DropIndexRequest struct {
	// Index ID
	TableId int64  `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	IndexId string `protobuf:"bytes,2,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
}

func (m *DropIndexRequest) Reset()                    { *m = DropIndexRequest{} }
func (m *DropIndexRequest) String() string            { return proto.CompactTextString(m) }
func (*DropIndexRequest) ProtoMessage()               {}
func (*DropIndexRequest) Descriptor() ([]byte, []int) { return fileDescriptorIndexer, []int{2} }

func (m *DropIndexRequest) GetTableId() int64 {
	if m != nil {
		return m.TableId
	}
	return 0
}

func (m *DropIndexRequest) GetIndexId() string {
	if m != nil {
		return m.IndexId
	}
	return ""
}

// DropIndexResponse is a response to the index drop request
type DropIndexResponse struct {
	// Operation result status code, 0 means success
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// Error message, only valid when status is non-zero
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (m *DropIndexResponse) Reset()                    { *m = DropIndexResponse{} }
func (m *DropIndexResponse) String() string            { return proto.CompactTextString(m) }
func (*DropIndexResponse) ProtoMessage()               {}
func (*DropIndexResponse) Descriptor() ([]byte, []int) { return fileDescriptorIndexer, []int{3} }

func (m *DropIndexResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DropIndexResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

// TableInfo represents table information
type TiCITableInfo struct {
	// Table ID
	TableId int64 `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// Table name
	TableName string `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	// Database name
	DatabaseName string `protobuf:"bytes,3,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	// Table version
	Version int64 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	// Column information
	Columns []*TiCIColumnInfo `protobuf:"bytes,5,rep,name=columns" json:"columns,omitempty"`
}

func (m *TiCITableInfo) Reset()                    { *m = TiCITableInfo{} }
func (m *TiCITableInfo) String() string            { return proto.CompactTextString(m) }
func (*TiCITableInfo) ProtoMessage()               {}
func (*TiCITableInfo) Descriptor() ([]byte, []int) { return fileDescriptorIndexer, []int{4} }

func (m *TiCITableInfo) GetTableId() int64 {
	if m != nil {
		return m.TableId
	}
	return 0
}

func (m *TiCITableInfo) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *TiCITableInfo) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *TiCITableInfo) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *TiCITableInfo) GetColumns() []*TiCIColumnInfo {
	if m != nil {
		return m.Columns
	}
	return nil
}

// ColumnInfo represents column information
type TiCIColumnInfo struct {
	// Column ID
	ColumnId int64 `protobuf:"varint,1,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	// Column name
	ColumnName string `protobuf:"bytes,2,opt,name=column_name,json=columnName,proto3" json:"column_name,omitempty"`
	// MySQL type
	Type int32 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	// Collation
	Collation int32 `protobuf:"varint,4,opt,name=collation,proto3" json:"collation,omitempty"`
	// Column length
	ColumnLength int32 `protobuf:"varint,5,opt,name=column_length,json=columnLength,proto3" json:"column_length,omitempty"`
	// Decimal places
	Decimal int32 `protobuf:"varint,6,opt,name=decimal,proto3" json:"decimal,omitempty"`
	// Flags
	Flag int32 `protobuf:"varint,7,opt,name=flag,proto3" json:"flag,omitempty"`
	// Enum elements
	Elems []string `protobuf:"bytes,8,rep,name=elems" json:"elems,omitempty"`
	// Default value
	DefaultVal []byte `protobuf:"bytes,9,opt,name=default_val,json=defaultVal,proto3" json:"default_val,omitempty"`
	// Whether it's a primary key
	IsPrimaryKey bool `protobuf:"varint,10,opt,name=is_primary_key,json=isPrimaryKey,proto3" json:"is_primary_key,omitempty"`
	// Whether it's an array
	IsArray bool `protobuf:"varint,11,opt,name=is_array,json=isArray,proto3" json:"is_array,omitempty"`
}

func (m *TiCIColumnInfo) Reset()                    { *m = TiCIColumnInfo{} }
func (m *TiCIColumnInfo) String() string            { return proto.CompactTextString(m) }
func (*TiCIColumnInfo) ProtoMessage()               {}
func (*TiCIColumnInfo) Descriptor() ([]byte, []int) { return fileDescriptorIndexer, []int{5} }

func (m *TiCIColumnInfo) GetColumnId() int64 {
	if m != nil {
		return m.ColumnId
	}
	return 0
}

func (m *TiCIColumnInfo) GetColumnName() string {
	if m != nil {
		return m.ColumnName
	}
	return ""
}

func (m *TiCIColumnInfo) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *TiCIColumnInfo) GetCollation() int32 {
	if m != nil {
		return m.Collation
	}
	return 0
}

func (m *TiCIColumnInfo) GetColumnLength() int32 {
	if m != nil {
		return m.ColumnLength
	}
	return 0
}

func (m *TiCIColumnInfo) GetDecimal() int32 {
	if m != nil {
		return m.Decimal
	}
	return 0
}

func (m *TiCIColumnInfo) GetFlag() int32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *TiCIColumnInfo) GetElems() []string {
	if m != nil {
		return m.Elems
	}
	return nil
}

func (m *TiCIColumnInfo) GetDefaultVal() []byte {
	if m != nil {
		return m.DefaultVal
	}
	return nil
}

func (m *TiCIColumnInfo) GetIsPrimaryKey() bool {
	if m != nil {
		return m.IsPrimaryKey
	}
	return false
}

func (m *TiCIColumnInfo) GetIsArray() bool {
	if m != nil {
		return m.IsArray
	}
	return false
}

// IndexInfo represents index information
type TiCIIndexInfo struct {
	// Index ID
	IndexId int64 `protobuf:"varint,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	// Index name
	IndexName string `protobuf:"bytes,2,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	// Index type (fulltext, custom)
	IndexType IndexType `protobuf:"varint,3,opt,name=index_type,json=indexType,proto3,enum=tipb.tici.IndexType" json:"index_type,omitempty"`
	// Index columns
	Columns []*TiCIColumnInfo `protobuf:"bytes,4,rep,name=columns" json:"columns,omitempty"`
	// Whether the index is unique
	IsUnique bool `protobuf:"varint,5,opt,name=is_unique,json=isUnique,proto3" json:"is_unique,omitempty"`
	// Parser information
	ParserInfo *ParserInfo `protobuf:"bytes,6,opt,name=parser_info,json=parserInfo" json:"parser_info,omitempty"`
	// Other index parameters
	OtherParams map[string]string `protobuf:"bytes,7,rep,name=other_params,json=otherParams" json:"other_params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *TiCIIndexInfo) Reset()                    { *m = TiCIIndexInfo{} }
func (m *TiCIIndexInfo) String() string            { return proto.CompactTextString(m) }
func (*TiCIIndexInfo) ProtoMessage()               {}
func (*TiCIIndexInfo) Descriptor() ([]byte, []int) { return fileDescriptorIndexer, []int{6} }

func (m *TiCIIndexInfo) GetIndexId() int64 {
	if m != nil {
		return m.IndexId
	}
	return 0
}

func (m *TiCIIndexInfo) GetIndexName() string {
	if m != nil {
		return m.IndexName
	}
	return ""
}

func (m *TiCIIndexInfo) GetIndexType() IndexType {
	if m != nil {
		return m.IndexType
	}
	return IndexType_UNKNOWN
}

func (m *TiCIIndexInfo) GetColumns() []*TiCIColumnInfo {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *TiCIIndexInfo) GetIsUnique() bool {
	if m != nil {
		return m.IsUnique
	}
	return false
}

func (m *TiCIIndexInfo) GetParserInfo() *ParserInfo {
	if m != nil {
		return m.ParserInfo
	}
	return nil
}

func (m *TiCIIndexInfo) GetOtherParams() map[string]string {
	if m != nil {
		return m.OtherParams
	}
	return nil
}

// ParserInfo represents parser information
type ParserInfo struct {
	// Parser type
	ParserType ParserType `protobuf:"varint,1,opt,name=parser_type,json=parserType,proto3,enum=tipb.tici.ParserType" json:"parser_type,omitempty"`
	// Parser parameters
	ParserParams map[string]string `protobuf:"bytes,2,rep,name=parser_params,json=parserParams" json:"parser_params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *ParserInfo) Reset()                    { *m = ParserInfo{} }
func (m *ParserInfo) String() string            { return proto.CompactTextString(m) }
func (*ParserInfo) ProtoMessage()               {}
func (*ParserInfo) Descriptor() ([]byte, []int) { return fileDescriptorIndexer, []int{7} }

func (m *ParserInfo) GetParserType() ParserType {
	if m != nil {
		return m.ParserType
	}
	return ParserType_UNKNOWN_PARSER
}

func (m *ParserInfo) GetParserParams() map[string]string {
	if m != nil {
		return m.ParserParams
	}
	return nil
}

// GetIndexProgressRequest is a request to get the progress of an index build
type GetIndexProgressRequest struct {
	// Table ID
	TableId int64 `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// Index ID
	IndexId int64 `protobuf:"varint,2,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
}

func (m *GetIndexProgressRequest) Reset()                    { *m = GetIndexProgressRequest{} }
func (m *GetIndexProgressRequest) String() string            { return proto.CompactTextString(m) }
func (*GetIndexProgressRequest) ProtoMessage()               {}
func (*GetIndexProgressRequest) Descriptor() ([]byte, []int) { return fileDescriptorIndexer, []int{8} }

func (m *GetIndexProgressRequest) GetTableId() int64 {
	if m != nil {
		return m.TableId
	}
	return 0
}

func (m *GetIndexProgressRequest) GetIndexId() int64 {
	if m != nil {
		return m.IndexId
	}
	return 0
}

// GetIndexProgressResponse is a response containing index build progress
type GetIndexProgressResponse struct {
	// Operation result status code, 0 means success
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// Error message, only valid when status is non-zero
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Number of documents indexed so far
	DocumentCount uint64 `protobuf:"varint,3,opt,name=document_count,json=documentCount,proto3" json:"document_count,omitempty"`
	// Build task state (PENDING, RUNNING, COMPLETED, FAILED)
	State string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	// Whether index has been uploaded to S3
	IsUploaded bool `protobuf:"varint,5,opt,name=is_uploaded,json=isUploaded,proto3" json:"is_uploaded,omitempty"`
	// Last S3 upload time in RFC3339 format
	LastUploadTime string `protobuf:"bytes,6,opt,name=last_upload_time,json=lastUploadTime,proto3" json:"last_upload_time,omitempty"`
	// S3 path where the index is stored
	S3Path []string `protobuf:"bytes,7,rep,name=s3_path,json=s3Path" json:"s3_path,omitempty"`
}

func (m *GetIndexProgressResponse) Reset()                    { *m = GetIndexProgressResponse{} }
func (m *GetIndexProgressResponse) String() string            { return proto.CompactTextString(m) }
func (*GetIndexProgressResponse) ProtoMessage()               {}
func (*GetIndexProgressResponse) Descriptor() ([]byte, []int) { return fileDescriptorIndexer, []int{9} }

func (m *GetIndexProgressResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetIndexProgressResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetIndexProgressResponse) GetDocumentCount() uint64 {
	if m != nil {
		return m.DocumentCount
	}
	return 0
}

func (m *GetIndexProgressResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *GetIndexProgressResponse) GetIsUploaded() bool {
	if m != nil {
		return m.IsUploaded
	}
	return false
}

func (m *GetIndexProgressResponse) GetLastUploadTime() string {
	if m != nil {
		return m.LastUploadTime
	}
	return ""
}

func (m *GetIndexProgressResponse) GetS3Path() []string {
	if m != nil {
		return m.S3Path
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateIndexRequest)(nil), "tipb.tici.CreateIndexRequest")
	proto.RegisterType((*CreateIndexResponse)(nil), "tipb.tici.CreateIndexResponse")
	proto.RegisterType((*DropIndexRequest)(nil), "tipb.tici.DropIndexRequest")
	proto.RegisterType((*DropIndexResponse)(nil), "tipb.tici.DropIndexResponse")
	proto.RegisterType((*TiCITableInfo)(nil), "tipb.tici.TiCITableInfo")
	proto.RegisterType((*TiCIColumnInfo)(nil), "tipb.tici.TiCIColumnInfo")
	proto.RegisterType((*TiCIIndexInfo)(nil), "tipb.tici.TiCIIndexInfo")
	proto.RegisterType((*ParserInfo)(nil), "tipb.tici.ParserInfo")
	proto.RegisterType((*GetIndexProgressRequest)(nil), "tipb.tici.GetIndexProgressRequest")
	proto.RegisterType((*GetIndexProgressResponse)(nil), "tipb.tici.GetIndexProgressResponse")
	proto.RegisterEnum("tipb.tici.IndexType", IndexType_name, IndexType_value)
	proto.RegisterEnum("tipb.tici.ParserType", ParserType_name, ParserType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for IndexerService service

type IndexerServiceClient interface {
	// CreateIndex creates a new index
	CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*CreateIndexResponse, error)
	// DropIndex removes an existing index
	DropIndex(ctx context.Context, in *DropIndexRequest, opts ...grpc.CallOption) (*DropIndexResponse, error)
	// GetIndexProgress retrieves the current progress of an index build
	GetIndexProgress(ctx context.Context, in *GetIndexProgressRequest, opts ...grpc.CallOption) (*GetIndexProgressResponse, error)
}

type indexerServiceClient struct {
	cc *grpc.ClientConn
}

func NewIndexerServiceClient(cc *grpc.ClientConn) IndexerServiceClient {
	return &indexerServiceClient{cc}
}

func (c *indexerServiceClient) CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*CreateIndexResponse, error) {
	out := new(CreateIndexResponse)
	err := grpc.Invoke(ctx, "/tipb.tici.IndexerService/CreateIndex", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexerServiceClient) DropIndex(ctx context.Context, in *DropIndexRequest, opts ...grpc.CallOption) (*DropIndexResponse, error) {
	out := new(DropIndexResponse)
	err := grpc.Invoke(ctx, "/tipb.tici.IndexerService/DropIndex", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexerServiceClient) GetIndexProgress(ctx context.Context, in *GetIndexProgressRequest, opts ...grpc.CallOption) (*GetIndexProgressResponse, error) {
	out := new(GetIndexProgressResponse)
	err := grpc.Invoke(ctx, "/tipb.tici.IndexerService/GetIndexProgress", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IndexerService service

type IndexerServiceServer interface {
	// CreateIndex creates a new index
	CreateIndex(context.Context, *CreateIndexRequest) (*CreateIndexResponse, error)
	// DropIndex removes an existing index
	DropIndex(context.Context, *DropIndexRequest) (*DropIndexResponse, error)
	// GetIndexProgress retrieves the current progress of an index build
	GetIndexProgress(context.Context, *GetIndexProgressRequest) (*GetIndexProgressResponse, error)
}

func RegisterIndexerServiceServer(s *grpc.Server, srv IndexerServiceServer) {
	s.RegisterService(&_IndexerService_serviceDesc, srv)
}

func _IndexerService_CreateIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServiceServer).CreateIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tipb.tici.IndexerService/CreateIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServiceServer).CreateIndex(ctx, req.(*CreateIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexerService_DropIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServiceServer).DropIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tipb.tici.IndexerService/DropIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServiceServer).DropIndex(ctx, req.(*DropIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexerService_GetIndexProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndexProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServiceServer).GetIndexProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tipb.tici.IndexerService/GetIndexProgress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServiceServer).GetIndexProgress(ctx, req.(*GetIndexProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IndexerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tipb.tici.IndexerService",
	HandlerType: (*IndexerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIndex",
			Handler:    _IndexerService_CreateIndex_Handler,
		},
		{
			MethodName: "DropIndex",
			Handler:    _IndexerService_DropIndex_Handler,
		},
		{
			MethodName: "GetIndexProgress",
			Handler:    _IndexerService_GetIndexProgress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tici/indexer.proto",
}

func (m *CreateIndexRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateIndexRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.IndexInfo != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(m.IndexInfo.Size()))
		n1, err := m.IndexInfo.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.TableInfo != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(m.TableInfo.Size()))
		n2, err := m.TableInfo.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	return i, nil
}

func (m *CreateIndexResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateIndexResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(m.Status))
	}
	if len(m.ErrorMessage) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(len(m.ErrorMessage)))
		i += copy(dAtA[i:], m.ErrorMessage)
	}
	if len(m.IndexId) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(len(m.IndexId)))
		i += copy(dAtA[i:], m.IndexId)
	}
	return i, nil
}

func (m *DropIndexRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DropIndexRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TableId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(m.TableId))
	}
	if len(m.IndexId) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(len(m.IndexId)))
		i += copy(dAtA[i:], m.IndexId)
	}
	return i, nil
}

func (m *DropIndexResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DropIndexResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(m.Status))
	}
	if len(m.ErrorMessage) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(len(m.ErrorMessage)))
		i += copy(dAtA[i:], m.ErrorMessage)
	}
	return i, nil
}

func (m *TiCITableInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TiCITableInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TableId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(m.TableId))
	}
	if len(m.TableName) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(len(m.TableName)))
		i += copy(dAtA[i:], m.TableName)
	}
	if len(m.DatabaseName) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(len(m.DatabaseName)))
		i += copy(dAtA[i:], m.DatabaseName)
	}
	if m.Version != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(m.Version))
	}
	if len(m.Columns) > 0 {
		for _, msg := range m.Columns {
			dAtA[i] = 0x2a
			i++
			i = encodeVarintIndexer(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *TiCIColumnInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TiCIColumnInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ColumnId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(m.ColumnId))
	}
	if len(m.ColumnName) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(len(m.ColumnName)))
		i += copy(dAtA[i:], m.ColumnName)
	}
	if m.Type != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(m.Type))
	}
	if m.Collation != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(m.Collation))
	}
	if m.ColumnLength != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(m.ColumnLength))
	}
	if m.Decimal != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(m.Decimal))
	}
	if m.Flag != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(m.Flag))
	}
	if len(m.Elems) > 0 {
		for _, s := range m.Elems {
			dAtA[i] = 0x42
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.DefaultVal) > 0 {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(len(m.DefaultVal)))
		i += copy(dAtA[i:], m.DefaultVal)
	}
	if m.IsPrimaryKey {
		dAtA[i] = 0x50
		i++
		if m.IsPrimaryKey {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.IsArray {
		dAtA[i] = 0x58
		i++
		if m.IsArray {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *TiCIIndexInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TiCIIndexInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.IndexId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(m.IndexId))
	}
	if len(m.IndexName) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(len(m.IndexName)))
		i += copy(dAtA[i:], m.IndexName)
	}
	if m.IndexType != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(m.IndexType))
	}
	if len(m.Columns) > 0 {
		for _, msg := range m.Columns {
			dAtA[i] = 0x22
			i++
			i = encodeVarintIndexer(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.IsUnique {
		dAtA[i] = 0x28
		i++
		if m.IsUnique {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.ParserInfo != nil {
		dAtA[i] = 0x32
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(m.ParserInfo.Size()))
		n3, err := m.ParserInfo.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if len(m.OtherParams) > 0 {
		for k, _ := range m.OtherParams {
			dAtA[i] = 0x3a
			i++
			v := m.OtherParams[k]
			mapSize := 1 + len(k) + sovIndexer(uint64(len(k))) + 1 + len(v) + sovIndexer(uint64(len(v)))
			i = encodeVarintIndexer(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintIndexer(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintIndexer(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	return i, nil
}

func (m *ParserInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ParserInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ParserType != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(m.ParserType))
	}
	if len(m.ParserParams) > 0 {
		for k, _ := range m.ParserParams {
			dAtA[i] = 0x12
			i++
			v := m.ParserParams[k]
			mapSize := 1 + len(k) + sovIndexer(uint64(len(k))) + 1 + len(v) + sovIndexer(uint64(len(v)))
			i = encodeVarintIndexer(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintIndexer(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintIndexer(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	return i, nil
}

func (m *GetIndexProgressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetIndexProgressRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TableId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(m.TableId))
	}
	if m.IndexId != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(m.IndexId))
	}
	return i, nil
}

func (m *GetIndexProgressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetIndexProgressResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(m.Status))
	}
	if len(m.ErrorMessage) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(len(m.ErrorMessage)))
		i += copy(dAtA[i:], m.ErrorMessage)
	}
	if m.DocumentCount != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(m.DocumentCount))
	}
	if len(m.State) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(len(m.State)))
		i += copy(dAtA[i:], m.State)
	}
	if m.IsUploaded {
		dAtA[i] = 0x28
		i++
		if m.IsUploaded {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.LastUploadTime) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintIndexer(dAtA, i, uint64(len(m.LastUploadTime)))
		i += copy(dAtA[i:], m.LastUploadTime)
	}
	if len(m.S3Path) > 0 {
		for _, s := range m.S3Path {
			dAtA[i] = 0x3a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func encodeVarintIndexer(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *CreateIndexRequest) Size() (n int) {
	var l int
	_ = l
	if m.IndexInfo != nil {
		l = m.IndexInfo.Size()
		n += 1 + l + sovIndexer(uint64(l))
	}
	if m.TableInfo != nil {
		l = m.TableInfo.Size()
		n += 1 + l + sovIndexer(uint64(l))
	}
	return n
}

func (m *CreateIndexResponse) Size() (n int) {
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovIndexer(uint64(m.Status))
	}
	l = len(m.ErrorMessage)
	if l > 0 {
		n += 1 + l + sovIndexer(uint64(l))
	}
	l = len(m.IndexId)
	if l > 0 {
		n += 1 + l + sovIndexer(uint64(l))
	}
	return n
}

func (m *DropIndexRequest) Size() (n int) {
	var l int
	_ = l
	if m.TableId != 0 {
		n += 1 + sovIndexer(uint64(m.TableId))
	}
	l = len(m.IndexId)
	if l > 0 {
		n += 1 + l + sovIndexer(uint64(l))
	}
	return n
}

func (m *DropIndexResponse) Size() (n int) {
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovIndexer(uint64(m.Status))
	}
	l = len(m.ErrorMessage)
	if l > 0 {
		n += 1 + l + sovIndexer(uint64(l))
	}
	return n
}

func (m *TiCITableInfo) Size() (n int) {
	var l int
	_ = l
	if m.TableId != 0 {
		n += 1 + sovIndexer(uint64(m.TableId))
	}
	l = len(m.TableName)
	if l > 0 {
		n += 1 + l + sovIndexer(uint64(l))
	}
	l = len(m.DatabaseName)
	if l > 0 {
		n += 1 + l + sovIndexer(uint64(l))
	}
	if m.Version != 0 {
		n += 1 + sovIndexer(uint64(m.Version))
	}
	if len(m.Columns) > 0 {
		for _, e := range m.Columns {
			l = e.Size()
			n += 1 + l + sovIndexer(uint64(l))
		}
	}
	return n
}

func (m *TiCIColumnInfo) Size() (n int) {
	var l int
	_ = l
	if m.ColumnId != 0 {
		n += 1 + sovIndexer(uint64(m.ColumnId))
	}
	l = len(m.ColumnName)
	if l > 0 {
		n += 1 + l + sovIndexer(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovIndexer(uint64(m.Type))
	}
	if m.Collation != 0 {
		n += 1 + sovIndexer(uint64(m.Collation))
	}
	if m.ColumnLength != 0 {
		n += 1 + sovIndexer(uint64(m.ColumnLength))
	}
	if m.Decimal != 0 {
		n += 1 + sovIndexer(uint64(m.Decimal))
	}
	if m.Flag != 0 {
		n += 1 + sovIndexer(uint64(m.Flag))
	}
	if len(m.Elems) > 0 {
		for _, s := range m.Elems {
			l = len(s)
			n += 1 + l + sovIndexer(uint64(l))
		}
	}
	l = len(m.DefaultVal)
	if l > 0 {
		n += 1 + l + sovIndexer(uint64(l))
	}
	if m.IsPrimaryKey {
		n += 2
	}
	if m.IsArray {
		n += 2
	}
	return n
}

func (m *TiCIIndexInfo) Size() (n int) {
	var l int
	_ = l
	if m.IndexId != 0 {
		n += 1 + sovIndexer(uint64(m.IndexId))
	}
	l = len(m.IndexName)
	if l > 0 {
		n += 1 + l + sovIndexer(uint64(l))
	}
	if m.IndexType != 0 {
		n += 1 + sovIndexer(uint64(m.IndexType))
	}
	if len(m.Columns) > 0 {
		for _, e := range m.Columns {
			l = e.Size()
			n += 1 + l + sovIndexer(uint64(l))
		}
	}
	if m.IsUnique {
		n += 2
	}
	if m.ParserInfo != nil {
		l = m.ParserInfo.Size()
		n += 1 + l + sovIndexer(uint64(l))
	}
	if len(m.OtherParams) > 0 {
		for k, v := range m.OtherParams {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovIndexer(uint64(len(k))) + 1 + len(v) + sovIndexer(uint64(len(v)))
			n += mapEntrySize + 1 + sovIndexer(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *ParserInfo) Size() (n int) {
	var l int
	_ = l
	if m.ParserType != 0 {
		n += 1 + sovIndexer(uint64(m.ParserType))
	}
	if len(m.ParserParams) > 0 {
		for k, v := range m.ParserParams {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovIndexer(uint64(len(k))) + 1 + len(v) + sovIndexer(uint64(len(v)))
			n += mapEntrySize + 1 + sovIndexer(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *GetIndexProgressRequest) Size() (n int) {
	var l int
	_ = l
	if m.TableId != 0 {
		n += 1 + sovIndexer(uint64(m.TableId))
	}
	if m.IndexId != 0 {
		n += 1 + sovIndexer(uint64(m.IndexId))
	}
	return n
}

func (m *GetIndexProgressResponse) Size() (n int) {
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovIndexer(uint64(m.Status))
	}
	l = len(m.ErrorMessage)
	if l > 0 {
		n += 1 + l + sovIndexer(uint64(l))
	}
	if m.DocumentCount != 0 {
		n += 1 + sovIndexer(uint64(m.DocumentCount))
	}
	l = len(m.State)
	if l > 0 {
		n += 1 + l + sovIndexer(uint64(l))
	}
	if m.IsUploaded {
		n += 2
	}
	l = len(m.LastUploadTime)
	if l > 0 {
		n += 1 + l + sovIndexer(uint64(l))
	}
	if len(m.S3Path) > 0 {
		for _, s := range m.S3Path {
			l = len(s)
			n += 1 + l + sovIndexer(uint64(l))
		}
	}
	return n
}

func sovIndexer(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozIndexer(x uint64) (n int) {
	return sovIndexer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CreateIndexRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIndexer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateIndexRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateIndexRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IndexInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIndexer
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.IndexInfo == nil {
				m.IndexInfo = &TiCIIndexInfo{}
			}
			if err := m.IndexInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIndexer
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TableInfo == nil {
				m.TableInfo = &TiCITableInfo{}
			}
			if err := m.TableInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIndexer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthIndexer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateIndexResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIndexer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateIndexResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateIndexResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorMessage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIndexer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrorMessage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IndexId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIndexer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IndexId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIndexer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthIndexer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DropIndexRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIndexer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DropIndexRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DropIndexRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableId", wireType)
			}
			m.TableId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TableId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IndexId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIndexer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IndexId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIndexer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthIndexer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DropIndexResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIndexer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DropIndexResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DropIndexResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorMessage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIndexer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrorMessage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIndexer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthIndexer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TiCITableInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIndexer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TiCITableInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TiCITableInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableId", wireType)
			}
			m.TableId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TableId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIndexer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TableName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DatabaseName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIndexer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DatabaseName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Columns", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIndexer
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Columns = append(m.Columns, &TiCIColumnInfo{})
			if err := m.Columns[len(m.Columns)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIndexer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthIndexer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TiCIColumnInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIndexer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TiCIColumnInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TiCIColumnInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ColumnId", wireType)
			}
			m.ColumnId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ColumnId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ColumnName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIndexer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ColumnName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collation", wireType)
			}
			m.Collation = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Collation |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ColumnLength", wireType)
			}
			m.ColumnLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ColumnLength |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decimal", wireType)
			}
			m.Decimal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Decimal |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flag", wireType)
			}
			m.Flag = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Flag |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Elems", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIndexer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Elems = append(m.Elems, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultVal", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthIndexer
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DefaultVal = append(m.DefaultVal[:0], dAtA[iNdEx:postIndex]...)
			if m.DefaultVal == nil {
				m.DefaultVal = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsPrimaryKey", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsPrimaryKey = bool(v != 0)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsArray", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsArray = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipIndexer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthIndexer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TiCIIndexInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIndexer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TiCIIndexInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TiCIIndexInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IndexId", wireType)
			}
			m.IndexId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IndexId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IndexName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIndexer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IndexName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IndexType", wireType)
			}
			m.IndexType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IndexType |= (IndexType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Columns", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIndexer
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Columns = append(m.Columns, &TiCIColumnInfo{})
			if err := m.Columns[len(m.Columns)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsUnique", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsUnique = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParserInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIndexer
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ParserInfo == nil {
				m.ParserInfo = &ParserInfo{}
			}
			if err := m.ParserInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OtherParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIndexer
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OtherParams == nil {
				m.OtherParams = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowIndexer
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowIndexer
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthIndexer
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowIndexer
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthIndexer
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipIndexer(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthIndexer
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.OtherParams[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIndexer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthIndexer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ParserInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIndexer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ParserInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ParserInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParserType", wireType)
			}
			m.ParserType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ParserType |= (ParserType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParserParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIndexer
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ParserParams == nil {
				m.ParserParams = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowIndexer
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowIndexer
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthIndexer
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowIndexer
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthIndexer
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipIndexer(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthIndexer
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ParserParams[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIndexer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthIndexer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetIndexProgressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIndexer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetIndexProgressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetIndexProgressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableId", wireType)
			}
			m.TableId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TableId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IndexId", wireType)
			}
			m.IndexId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IndexId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipIndexer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthIndexer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetIndexProgressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIndexer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetIndexProgressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetIndexProgressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorMessage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIndexer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrorMessage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DocumentCount", wireType)
			}
			m.DocumentCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DocumentCount |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIndexer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.State = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsUploaded", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsUploaded = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUploadTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIndexer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastUploadTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field S3Path", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIndexer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.S3Path = append(m.S3Path, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIndexer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthIndexer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIndexer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIndexer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIndexer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthIndexer
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowIndexer
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipIndexer(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthIndexer = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIndexer   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("tici/indexer.proto", fileDescriptorIndexer) }

var fileDescriptorIndexer = []byte{
	// 1000 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xce, 0xda, 0xf1, 0xcf, 0x1e, 0x3b, 0xd6, 0x76, 0x08, 0x74, 0xe3, 0xb6, 0x21, 0x72, 0x41,
	0x98, 0x5e, 0xa4, 0x52, 0x2c, 0x01, 0xe2, 0x02, 0x14, 0xd2, 0x84, 0x46, 0x75, 0x63, 0x6b, 0x63,
	0x03, 0x12, 0x17, 0xab, 0x89, 0x77, 0xe2, 0xac, 0xd8, 0xbf, 0xce, 0x8c, 0x23, 0x7c, 0x8d, 0xc4,
	0x23, 0x20, 0x5e, 0x86, 0x7b, 0x24, 0x6e, 0x90, 0x78, 0x01, 0x14, 0x5e, 0x82, 0x4b, 0x34, 0x67,
	0x66, 0xed, 0x75, 0x7e, 0x2a, 0x40, 0xbd, 0x3b, 0xf3, 0x9d, 0x9f, 0x39, 0xe7, 0x9b, 0x6f, 0x67,
	0x07, 0x88, 0x0c, 0x27, 0xe1, 0xd3, 0x30, 0x09, 0xd8, 0xf7, 0x8c, 0xef, 0x66, 0x3c, 0x95, 0x29,
	0xb1, 0x65, 0x98, 0x9d, 0xed, 0x2a, 0x47, 0x7b, 0x73, 0x9a, 0x4e, 0x53, 0x44, 0x9f, 0x2a, 0x4b,
	0x07, 0x74, 0x7e, 0xb4, 0x80, 0x1c, 0x70, 0x46, 0x25, 0x3b, 0x56, 0x89, 0x1e, 0x7b, 0x35, 0x63,
	0x42, 0x92, 0x8f, 0x01, 0xb0, 0x90, 0x1f, 0x26, 0xe7, 0xa9, 0x6b, 0xed, 0x58, 0xdd, 0xc6, 0x9e,
	0xbb, 0xbb, 0x28, 0xb6, 0x3b, 0x0a, 0x0f, 0x8e, 0x31, 0xe1, 0x38, 0x39, 0x4f, 0x3d, 0x3b, 0xcc,
	0x4d, 0x95, 0x28, 0xe9, 0x59, 0xc4, 0x74, 0x62, 0xe9, 0xd6, 0xc4, 0x91, 0x0a, 0xd0, 0x89, 0x32,
	0x37, 0x3b, 0x31, 0xbc, 0xb5, 0xd2, 0x87, 0xc8, 0xd2, 0x44, 0x30, 0xf2, 0x0e, 0x54, 0x85, 0xa4,
	0x72, 0x26, 0xb0, 0x89, 0x8a, 0x67, 0x56, 0xe4, 0x31, 0x6c, 0x30, 0xce, 0x53, 0xee, 0xc7, 0x4c,
	0x08, 0x3a, 0x65, 0xb8, 0x95, 0xed, 0x35, 0x11, 0x7c, 0xa9, 0x31, 0xb2, 0x05, 0x75, 0x33, 0x45,
	0xe0, 0x96, 0xd1, 0x5f, 0xd3, 0x9d, 0x06, 0x9d, 0xe7, 0xe0, 0x3c, 0xe3, 0x69, 0xb6, 0x32, 0xf4,
	0x16, 0xd4, 0x4d, 0xef, 0x01, 0xee, 0x56, 0xf6, 0x6a, 0xba, 0xbf, 0x60, 0xa5, 0x52, 0x69, 0xb5,
	0xd2, 0x10, 0xee, 0x15, 0x2a, 0xbd, 0x81, 0xb6, 0x3b, 0xbf, 0x58, 0xb0, 0xb1, 0xc2, 0xd3, 0xeb,
	0x3a, 0x7b, 0x94, 0x13, 0x9e, 0xd0, 0x38, 0x2f, 0xa7, 0x69, 0x3d, 0xa1, 0x31, 0x53, 0x1b, 0x06,
	0x54, 0xd2, 0x33, 0x2a, 0x4c, 0x84, 0xe6, 0xa1, 0x99, 0x83, 0x18, 0xe4, 0x42, 0xed, 0x92, 0x71,
	0x11, 0xa6, 0x89, 0xbb, 0xae, 0xab, 0x9b, 0x25, 0xe9, 0x41, 0x6d, 0x92, 0x46, 0xb3, 0x38, 0x11,
	0x6e, 0x65, 0xa7, 0xdc, 0x6d, 0xec, 0x6d, 0x5d, 0x3b, 0xcb, 0x03, 0xf4, 0xe2, 0x61, 0xe6, 0x91,
	0x9d, 0xdf, 0x4a, 0xd0, 0x5a, 0xf5, 0x91, 0x07, 0x60, 0x6b, 0xef, 0x72, 0x82, 0xba, 0x06, 0x8e,
	0x03, 0xf2, 0x2e, 0x34, 0x8c, 0xb3, 0x30, 0x03, 0x68, 0x08, 0xfb, 0x23, 0xb0, 0x2e, 0xe7, 0x99,
	0xee, 0xbd, 0xe2, 0xa1, 0x4d, 0x1e, 0x62, 0xc5, 0x88, 0xca, 0xbc, 0xeb, 0x8a, 0xb7, 0x04, 0xd4,
	0xd8, 0xa6, 0x64, 0xc4, 0x92, 0xa9, 0xbc, 0x70, 0x2b, 0x18, 0xd1, 0xd4, 0x60, 0x1f, 0x31, 0x35,
	0x76, 0xc0, 0x26, 0x61, 0x4c, 0x23, 0xb7, 0x8a, 0xee, 0x7c, 0xa9, 0x36, 0x3c, 0x8f, 0xe8, 0xd4,
	0xad, 0xe9, 0x0d, 0x95, 0x4d, 0x36, 0xa1, 0xc2, 0x22, 0x16, 0x0b, 0xb7, 0xbe, 0x53, 0xee, 0xda,
	0x9e, 0x5e, 0xa8, 0xde, 0x03, 0x76, 0x4e, 0x67, 0x91, 0xf4, 0x2f, 0x69, 0xe4, 0xda, 0x3b, 0x56,
	0xb7, 0xe9, 0x81, 0x81, 0xbe, 0xa2, 0x11, 0x79, 0x0f, 0x5a, 0xa1, 0xf0, 0x33, 0x1e, 0xc6, 0x94,
	0xcf, 0xfd, 0xef, 0xd8, 0xdc, 0x85, 0x1d, 0xab, 0x5b, 0xf7, 0x9a, 0xa1, 0x18, 0x6a, 0xf0, 0x05,
	0x9b, 0xa3, 0xbe, 0x84, 0x4f, 0x39, 0xa7, 0x73, 0xb7, 0x81, 0xfe, 0x5a, 0x28, 0xf6, 0xd5, 0xb2,
	0xf3, 0x53, 0x59, 0xab, 0x61, 0xf1, 0xb9, 0xad, 0x88, 0xd1, 0xa8, 0xc1, 0x88, 0x51, 0xa9, 0x41,
	0xbb, 0x8a, 0x6a, 0x40, 0x04, 0x89, 0xec, 0xe5, 0xee, 0x05, 0x9d, 0xad, 0xbd, 0xcd, 0xc2, 0x89,
	0xe2, 0x1e, 0xa3, 0x79, 0xc6, 0x4c, 0x92, 0x32, 0x8b, 0x1a, 0x58, 0xff, 0xb7, 0x1a, 0x50, 0x07,
	0x1e, 0x0a, 0x7f, 0x96, 0x84, 0xaf, 0x66, 0x0c, 0xc9, 0xaf, 0x7b, 0xf5, 0x50, 0x8c, 0x71, 0x4d,
	0x3e, 0x82, 0x46, 0x46, 0xb9, 0x60, 0x5c, 0xdf, 0x12, 0x55, 0xbc, 0x25, 0xde, 0x2e, 0x54, 0x1d,
	0xa2, 0x17, 0x2b, 0x42, 0xb6, 0xb0, 0x49, 0x1f, 0x9a, 0xa9, 0xbc, 0x60, 0xdc, 0xcf, 0x28, 0xa7,
	0xb1, 0x70, 0x6b, 0xd8, 0xce, 0x87, 0x77, 0xdd, 0x4b, 0xbb, 0x03, 0x15, 0x3c, 0xc4, 0xd8, 0xc3,
	0x44, 0xf2, 0xb9, 0xd7, 0x48, 0x97, 0x48, 0xfb, 0x33, 0x70, 0xae, 0x07, 0x10, 0x07, 0xca, 0xea,
	0x88, 0x2c, 0x24, 0x4e, 0x99, 0xea, 0xd8, 0x2f, 0x69, 0x34, 0xcb, 0xc9, 0xd4, 0x8b, 0x4f, 0x4b,
	0x9f, 0x58, 0x9d, 0x3f, 0x2c, 0x80, 0x65, 0xa3, 0x85, 0xa1, 0x90, 0x5c, 0x0b, 0xc9, 0xbd, 0x39,
	0x14, 0xb2, 0x6b, 0x86, 0x42, 0x7a, 0xfb, 0xb0, 0x61, 0xf2, 0xcc, 0x54, 0x25, 0x9c, 0xea, 0x83,
	0x5b, 0xe9, 0x30, 0x66, 0x71, 0xa6, 0x66, 0x56, 0x80, 0xda, 0x9f, 0xc3, 0xbd, 0x1b, 0x21, 0xff,
	0x69, 0xaa, 0x01, 0xdc, 0xff, 0x92, 0x49, 0xe4, 0x70, 0xc8, 0xd3, 0x29, 0x67, 0x42, 0xfc, 0x8f,
	0xfb, 0x71, 0x29, 0xc9, 0xce, 0xdf, 0x16, 0xb8, 0x37, 0x2b, 0xbe, 0x89, 0xeb, 0xfd, 0x7d, 0x68,
	0x05, 0xe9, 0x64, 0x16, 0xb3, 0x44, 0xfa, 0x93, 0x74, 0x96, 0x48, 0x54, 0xf4, 0xba, 0xb7, 0x91,
	0xa3, 0x07, 0x0a, 0x54, 0xb3, 0xaa, 0xaa, 0x0c, 0x6f, 0x09, 0xdb, 0xd3, 0x0b, 0xf5, 0xe1, 0x2a,
	0x81, 0x66, 0x51, 0x4a, 0x03, 0x16, 0x18, 0x89, 0x42, 0x28, 0xc6, 0x06, 0x21, 0x5d, 0x70, 0x22,
	0x2a, 0xa4, 0x09, 0xf1, 0x65, 0x18, 0x33, 0x54, 0xaa, 0xed, 0xb5, 0x14, 0xae, 0xe3, 0x46, 0x61,
	0xcc, 0xc8, 0x7d, 0xa8, 0x89, 0x9e, 0x9f, 0x51, 0x79, 0x81, 0x8a, 0xb4, 0xbd, 0xaa, 0xe8, 0x0d,
	0xa9, 0xbc, 0x78, 0xd2, 0x03, 0x7b, 0xf1, 0x45, 0x91, 0x06, 0xd4, 0xc6, 0x27, 0x2f, 0x4e, 0x06,
	0x5f, 0x9f, 0x38, 0x6b, 0x64, 0x03, 0xec, 0xa3, 0x71, 0xbf, 0xef, 0x8f, 0x0e, 0xbf, 0x19, 0x39,
	0x16, 0x01, 0xa8, 0x1e, 0x8c, 0x4f, 0x47, 0x83, 0x97, 0x4e, 0xe9, 0xc9, 0x51, 0xae, 0x2a, 0xcc,
	0x22, 0xd0, 0x32, 0x59, 0xfe, 0x70, 0xdf, 0x3b, 0x3d, 0xf4, 0x9c, 0x35, 0x85, 0x3d, 0x3b, 0x3c,
	0xda, 0x1f, 0xf7, 0x47, 0x39, 0x66, 0x11, 0x07, 0x9a, 0x83, 0xd1, 0xf3, 0x43, 0x2f, 0x47, 0x4a,
	0x7b, 0x3f, 0x94, 0xa0, 0x75, 0xac, 0x1f, 0x03, 0xa7, 0x8c, 0x5f, 0x86, 0x13, 0x25, 0xb5, 0x46,
	0xe1, 0x1f, 0x4b, 0x1e, 0x15, 0x24, 0x76, 0xf3, 0x0d, 0xd0, 0xde, 0xbe, 0xcb, 0x6d, 0xce, 0xee,
	0x08, 0xec, 0xc5, 0x8f, 0x8f, 0x3c, 0x28, 0x04, 0x5f, 0xff, 0xb1, 0xb6, 0x1f, 0xde, 0xee, 0x34,
	0x75, 0xbe, 0x05, 0xe7, 0xba, 0x3e, 0x48, 0xa7, 0x90, 0x71, 0x87, 0x1c, 0xdb, 0x8f, 0x5f, 0x1b,
	0xa3, 0x8b, 0x7f, 0xe1, 0xfc, 0x7a, 0xb5, 0x6d, 0xfd, 0x7e, 0xb5, 0x6d, 0xfd, 0x79, 0xb5, 0x6d,
	0xfd, 0xfc, 0xd7, 0xf6, 0xda, 0x59, 0x15, 0x1f, 0x3e, 0xbd, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x48, 0x3a, 0x5e, 0xfe, 0x2f, 0x09, 0x00, 0x00,
}
